apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abc
  template:
    metadata:
      labels:
        app: abc
    spec:
      containers:
      - image: okteto.dev/abc:latest
        name: abc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1aa29ce6-a110-4747-8299-277880dcccc9"
        - name: Vless_Path
          value: "/fgh76ugjyu"
        - name: Vmess_UUID
          value: "1aa29ce6-a110-4747-8299-277880dcccc9"
        - name: Vmess_Path
          value: "/fdbjui75u5d"
        - name: Share_Path
          value: "/v2link"
